/**
 * Country list for the "country of residence" field (3 Aug standup — a free
 * text box produced too many spellings of the same country to filter on).
 *
 * Stored as the plain English name rather than an ISO code: the value shows up
 * verbatim in the admin console and the participants CSV export, and a code
 * would mean a lookup at every one of those call sites for no real gain.
 *
 * The UK is pinned to the top since it's the overwhelming majority of the
 * platform's users; the rest are alphabetical.
 */
export const COUNTRY_SUGGESTIONS = ["United Kingdom", "Ireland"] as const;

export const COUNTRIES: readonly string[] = [
  "United Kingdom",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo (Democratic Republic)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

let codeByName: Map<string, string> | null = null;

/** Our names that the runtime spells differently ("St. Lucia", "Türkiye", …). */
const CODE_ALIASES: Record<string, string> = {
  "antigua and barbuda": "AG",
  "bosnia and herzegovina": "BA",
  congo: "CG",
  "congo (democratic republic)": "CD",
  "hong kong": "HK",
  "ivory coast": "CI",
  macao: "MO",
  myanmar: "MM",
  palestine: "PS",
  "saint kitts and nevis": "KN",
  "saint lucia": "LC",
  "saint vincent and the grenadines": "VC",
  "sao tome and principe": "ST",
  "trinidad and tobago": "TT",
  turkey: "TR",
};

/**
 * ISO 3166-1 alpha-2 code for a country name from COUNTRIES (Stripe needs the
 * code on a customer's address). Built once from the runtime's own region
 * names; returns null when a name has no match, and the address is then sent
 * without a country rather than with a wrong one.
 */
export function countryCode(name: string | null | undefined): string | null {
  if (!name) return null;
  if (!codeByName) {
    codeByName = new Map();
    const names = new Intl.DisplayNames(["en"], { type: "region" });
    const A = "A".charCodeAt(0);
    for (let i = 0; i < 26; i++) {
      for (let j = 0; j < 26; j++) {
        const code = String.fromCharCode(A + i, A + j);
        let label: string | undefined;
        try {
          label = names.of(code);
        } catch {
          continue;
        }
        // First code wins: GB before the reserved "UK", which also reads "United Kingdom".
        const key = label?.toLowerCase();
        if (key && label !== code && !codeByName.has(key)) codeByName.set(key, code);
      }
    }
  }
  const key = name.toLowerCase();
  return CODE_ALIASES[key] ?? codeByName.get(key) ?? null;
}
